export const MILESTONES = [
  {
    year: 2026,
    age: 32,
    label: "HIEN TAI",
    phase: "Xay nen tang",
    color: "#00d4ff",
    image: "/milestone_2027.png",
    highlights: [
      "Dang xay AI Agent (Amazon, POD, Marketing)",
      "3 video/tuan, 2.500 members FreedomBuilder",
      "Chay 21km/3h, bat dau hoc boi",
      "Thu nhap ~$60K/nam",
    ],
    details: {
      health: "Chay 21km, gym, dap xe. Boi con kem",
      career: "Founder/Developer/YouTuber",
      finance: "$60K — Luong + freelance",
      family: "Con trai 7t, con gai 1t. 30p/ngay day con",
    },
  },
  {
    year: 2027,
    age: 33,
    label: "KHOI DAU",
    phase: "Nam 1 — First Revenue",
    color: "#00d4ff",
    image: "/milestone_2027.png",
    highlights: [
      "Half Marathon chinh thuc",
      "Sach #1 xuat ban",
      "Khach hang tra tien dau tien",
      "$1M doanh thu — 10K+ FreedomBuilder",
    ],
    details: {
      health: "Half Marathon dau tien. Bat dau hoc boi nghiem tuc",
      career: "CEO + Educator. San pham AI Agent tra phi. Sach #1",
      finance: "$1M doanh thu, $500K+ tai san",
      family: "Con trai 8t, con gai 2t. Family trip nuoc ngoai dau tien",
    },
  },
  {
    year: 2029,
    age: 35,
    label: "TANG TOC",
    phase: "Nam 3 — Scale Up",
    color: "#ffd700",
    image: "/milestone_2029.png",
    highlights: [
      "Full Marathon 42km",
      "50K+ community",
      "$3-5M doanh thu",
      "Bat dau dau tu startup",
    ],
    details: {
      health: "Full Marathon. Boi thanh thao. Bat dau tap Triathlon",
      career: "CEO + Investor nho. Portfolio 3-5 AI Agent san pham",
      finance: "$3-5M doanh thu, $10M tai san",
      family: "Con trai 10t, con gai 4t. Family workation 2-3 lan/nam",
    },
  },
  {
    year: 2031,
    age: 37,
    label: "BUT PHA",
    phase: "Nam 5 — Freedom",
    color: "#ff9100",
    image: "/milestone_2031.png",
    highlights: [
      "Half Ironman 70.3",
      "<10 nguoi + AI agents tu van hanh",
      "$30M tai san",
      "Speaker quoc te",
    ],
    details: {
      health: "Half Ironman. The hinh 6 mui. Check-up dinh ky",
      career: "CEO chien luoc. Dau tu 5-10 startup. Speaking quoc te",
      finance: "$5-10M doanh thu, $30M tai san",
      family: "Con trai 12t, con gai 6t. Con bat dau hoc lap trinh/AI",
    },
  },
  {
    year: 2036,
    age: 42,
    label: "TU DO",
    phase: "Nam 10 — Legacy",
    color: "#00e676",
    image: "/milestone_2036.png",
    highlights: [
      "Full Ironman 140.6 Finisher",
      "<5 nguoi, $100M doanh thu",
      "Digital nomad hoan toan",
      "Quy dau tu + Quy tu thien",
    ],
    details: {
      health: "Ironman Finisher. 6 mui, suc khoe tuyet voi",
      career: "CEO + Nha dau tu + Educator. Thuong hieu nhu Dan Martell",
      finance: "$10-20M doanh thu, $100M tai san. Tu do tai chinh",
      family: "Con trai 17t chon DH. Con gai 11t. Du lich the gioi cung gia dinh",
    },
  },
];

export const LIFE_AREAS = [
  {
    name: "Suc khoe & The chat",
    key: "health",
    icon: "🏃",
    color: "#00e676",
    current: "Chay 21km/3h",
    target: "Ironman 140.6 Finisher",
    progress: 20,
  },
  {
    name: "Su nghiep & Cong viec",
    key: "career",
    icon: "🚀",
    color: "#448aff",
    current: "Founder/Developer",
    target: "CEO $100M + Investor",
    progress: 15,
  },
  {
    name: "Tai chinh",
    key: "finance",
    icon: "💰",
    color: "#ffd740",
    current: "$60K/nam",
    target: "$100M tong tai san",
    progress: 5,
  },
  {
    name: "Gia dinh",
    key: "family",
    icon: "👨‍👩‍👧‍👦",
    color: "#ff6090",
    current: "Con trai 7t, con gai 1t",
    target: "Gia dinh hanh phuc, du lich the gioi",
    progress: 40,
  },
  {
    name: "Phat trien ban than",
    key: "growth",
    icon: "📚",
    color: "#b388ff",
    current: "Hoc 4-6h sang",
    target: "Speaker quoc te, Author",
    progress: 25,
  },
  {
    name: "Trai nghiem & Giai tri",
    key: "experience",
    icon: "✈️",
    color: "#ff9100",
    current: "VN-based",
    target: "Digital nomad, resort lifestyle",
    progress: 10,
  },
  {
    name: "Dong gop & Cong dong",
    key: "community",
    icon: "🤝",
    color: "#69f0ae",
    current: "2.500 members",
    target: "200K+ members, Quy tu thien",
    progress: 10,
  },
];

export const FINANCIAL_DATA = [
  { year: 2026, revenue: 60, assets: 50, label: "$60K" },
  { year: 2027, revenue: 1000, assets: 500, label: "$1M" },
  { year: 2029, revenue: 5000, assets: 10000, label: "$5M" },
  { year: 2031, revenue: 10000, assets: 30000, label: "$30M" },
  { year: 2036, revenue: 20000, assets: 100000, label: "$100M" },
];

export const EXTRA_IMAGES = [
  { key: "family_2036", src: "/family_2036.png", label: "Gia dinh du lich the gioi" },
  { key: "workspace", src: "/workspace_future.png", label: "Workspace tuong lai" },
  { key: "ironman", src: "/ironman_finish.png", label: "Ironman Finisher" },
  { key: "community", src: "/community_impact.png", label: "FreedomBuilder 200K+" },
];
